_target_: models.salun.SalUn

base_model: "CompVis/stable-diffusion-v1-4"
device: "cuda"
torch_dtype: "float32"
safety_checker: null
unet_weights: "../weights/Salun-Nudity-Diffusers-UNet.pt"
name: "SalUn"