_target_: models.erase_diff.EraseDiff

base_model: "CompVis/stable-diffusion-v1-4"
device: "cuda"
torch_dtype: "float32"
safety_checker: null
unet_weights: "weights/EraseDiff/EraseDiff-Nudity-Diffusers-UNet.pt"
name: "EraseDiff"