_target_: models.esd.ESD

base_model: "CompVis/stable-diffusion-v1-4"
device: "cuda"
torch_dtype: "float16"
safety_checker: null
unet_weights: "C:/Users/polowczyk/Desktop/repozytoria/reunlearning/ESD/ckpt/diffusers-nudity-ESDu1-UNET.pt"
name: "ESD"