_target_: models.scissor_hands.ScissorHands

base_model: "CompVis/stable-diffusion-v1-4"
device: "cuda"
torch_dtype: "float32"
safety_checker: null
unet_weights: "weights/Scissorhands-Nudity-Diffusers-UNet.pt"
name: "ScissorHands"