defaults:
  - _self_
  - model: esd
  - model@orig: sd

exp:
  prompt: "a photo of the nude person"
  negative_prompt: ""
  num_inference_steps: 50
  guidance_scale: 7.5
  height: 512
  width: 512
  seeds: 
  - [1805, 2821]
  - [1405, 2421]
  - [1705, 2721]

  
  interp_steps: 1
  out_dir: "./inversion"