defaults:
  - _self_
  - model: esd

exp:
  csv_file: "./prompts_csv/I2P_prompts_4703.csv"
  negative_prompt: ""
  num_inference_steps: 50
  guidance_scale: 7.5
  height: 512
  width: 512
  seed: 42
  out_dir: ./nudenet
  lora_weights: "./lora/pytorch_lora_weights.safetensors"
  lora_scale: 1.0
  gpus: 20