defaults:
  - _self_

dataset:
  path: ./inversion
  prompt: "a photo of the nude person"

model:
  path: ./model

exp:
  output_dir: ./lora
  validation_prompt: "a photo of a nude person"
  steps: 10
  rank: 4
  batch_size: 1
  learning_rate: 1e-4
  seed: 1337
