defaults:
  - _self_
  - model: esd

exp:
  prompt: "a photo of the nude person"
  negative_prompt: ""
  num_inference_steps: 50
  guidance_scale: 7.5
  height: 512
  width: 512
  seed: 42
  out_dir: ./nudenet
  num_images: 2
  lora_weights: "./lora/pytorch_lora_weights.safetensors"
  lora_scale: 1.0